### ISSUE TITLE
PreFlight failed; not loading daemon

### ISSUE THREAD

**Issue by artburkart** [gamechanger/dusty#430]
```
$ bash -c "`curl -L https://github.com/gamechanger/dusty/releases/download/0.3.0/install.sh`"
... bunch of output ...
dusty.preflight.PreflightException: Preflight Errors:
	Executable not found: nginx
Preflight failed; not loading daemon
```

It appears that installation of nginx is required before installing Dusty, but it doesn't say so in the installation guide.

I solved it with `brew install nginx`

**Comment by thieman** [comment]
The instructions for nginx install are removed in the latest docs since it's no longer required in 0.3.0. The stable docs should be the same as 0.3.0, and should still have the old instructions for nginx. You can see that install document here: http://dusty.readthedocs.org/en/stable/installation/

Do you remember how you got to the install page without those instructions? It's possible we have a link out there to the latest docs that should be fixed to point to stable. Thanks for the report!

**Comment by artburkart** [comment]
Oh, well I went to [http://dusty.gc.com/](http://dusty.gc.com/), clicked on ["Get Started Now"](https://dusty.readthedocs.org/en/latest/installation/), then installed `docker-compose` (since `boot2docker` was already installed), finally I ran:
`bash -c "`curl -L https://github.com/gamechanger/dusty/releases/download/0.3.0/install.sh`"`

**Comment by thieman** [comment]
Ah, yeah, that'll definitely do it. I'll fix the links on the homepage shortly. I also clarified the link in our readme a bit.

**Comment by artburkart** [comment]
:+1:

**Comment by thieman** [comment]
I fixed the links on the homepage and on the Why We Wrote Dusty blog post to point to stable. Think that should be all of them.
