### ISSUE TITLE
dusty doctor command for common VBox problems

### ISSUE THREAD

**Issue by thieman** [gamechanger/dusty#653]
VirtualBox constantly runs into problems that are hard to recover from, making Dusty inoperable for users. Since we aim to include all functionality in Dusty and not resort to having the users running manual VBox, Machine, and Compose commands, we should bring these common debugging steps into Dusty to attempt to get VBox back into a good state when this happens.

I'd like to add a `dusty doctor` command that runs the following remediation steps:

1. Stop the Dusty VM
2. Delete the host-only interface assigned to the VM (these are [the worst things ever](https://github.com/docker/machine/search?utf8=%E2%9C%93&q=host-only))
3. Start the VM up again
4. See if `docker-machine env dusty` works, and if not run `docker-machine regenerate-certs dusty`

@paetling RFC

**Comment by paetling** [comment]
My fear with this command is that it becomes bloated.  We add a fix here and a fix there and eventually this thing tries to fix a dozen different things and takes a few minutes.   Do you think it would be worth having some more fine tuned control around this tool.  So instead of just running `dusty doctor` you run, `dusty docker fix certs` or `dusty docker fix all`?

Maybe we implement the fix everything functionality right now and can approach specific commands as we add more?

I like the idea in general.

**Comment by thieman** [comment]
I'm fine with it taking a few minutes if it fixes the known VirtualBox problems. I don't think it'd make sense to split into subcommands unless the user knows exactly which problem they're encountering, which is not going to be the case.

**Comment by thieman** [comment]
Closed by #654
