### ISSUE TITLE
Services and base images from private registries

### ISSUE THREAD

**Issue by morganjbruce** [gamechanger/dusty#659]
I'm having some trouble running `dusty up` in the following scenarios:

- Defining a service with an image from a private registry.
- Defining an app with `build .`, where the Dockerfile has a FROM entry referring to a container in a private registry

In both, I get the error:

```
ERROR: Get https://REGISTRY_URL/v2/CONTAINER/manifests/TAG: no basic auth credentials
ERROR: Command 'docker-compose -f /etc/dusty/compose/docker-compose.yml -p dusty up -d' returned non-zero exit status 256
```

However, running that docker-compose command by itself works without any trouble.

I've also had a read through #626 and made sure docker is logged in and that the config.json files are being updated.

Dump output here: https://gist.github.com/morganjbruce/2646e29bac94191bb251

Any suggestions on what to investigate?

**Comment by thieman** [comment]
First off, thank you for a well-written submission and for providing your `dusty dump` output. :smile: 

My first thought would be whether Dusty can successfully pull the image in the private repository if you provide it as the `image` key in the spec rather than using the `build` key. Perhaps the failure or success there might point us in the right direction.

**Comment by thieman** [comment]
This was the only match I could find for your issue in Compose and it's rather recent (2 weeks), you might want to try downgrading Compose a few versions to see if the issue still exists. https://github.com/docker/compose/issues/3037

**Comment by morganjbruce** [comment]
Forgot to include my app/service definitions (where REPO = my private repo):

app.yml
```
repo: somewhere.git
mount: /somewhere
build: .
```

somewhere.git includes a Dockerfile that defines a base in a private repo: `FROM REPO/ruby-2.1.5:latest`

postgres.yml
```
image: REPO/postgres:origin_master
```

Running the docker-compose command with --verbose gives the following output about authentication:

```
compose.cli.verbose_proxy.proxy_callable: docker pull <- (u'REPO/postgres', tag=u'origin_master', stream=True)
docker.api.image.pull: Looking for auth config
docker.auth.auth.resolve_authconfig: Looking for auth entry for u'REPO'
docker.auth.auth.resolve_authconfig: Found u'REPO'
docker.api.image.pull: Found auth config
compose.cli.verbose_proxy.proxy_callable: docker pull -> <generator object _stream_helper at 0x10554a730>
origin_master: Pulling from postgres
```

**Comment by morganjbruce** [comment]
Trying different version combinations:

1. Initial configuration - `dusty 0.7.0 | docker-compose 1.6.2` - doesn't work
2. Downgraded Compose - `dusty 0.7.0 | docker-compose 1.5.2` - doesn't work
3. Downgraded Dusty - `dusty 0.6.5 | docker-compose 1.5.2` - works correctly

Unfortunately docker-compose 1.6.2 isn't compatible with dusty 0.6.5, as the `--allow-insecure-ssl` flag was removed in compose 1.6.

**Comment by morganjbruce** [comment]
After some messing around, I think the problem is down to how launchctl sets environment variables (and how they're subsequently picked up in docker-py).

When I run Dusty from source, it works:

```bash
# terminal 1
python setup.py install
sudo dusty -d
# terminal 2
dusty up
```

But when I install the daemon using launchctl, it doesn't:

```bash
sudo chown root /Library/LaunchDaemons/com.gamechanger.dusty.plist
sudo chgrp wheel /Library/LaunchDaemons/com.gamechanger.dusty.plist
sudo launchctl load /Library/LaunchDaemons/com.gamechanger.dusty.plist
dusty up
```

The `find_config_file` method in [docker-py](https://github.com/docker/docker-py/blob/master/docker/auth/auth.py#L147) determines which path to look at for the config.json file. Unless overriden by a `DOCKER_CONFIG` environment variable, this looks at `os.path.join(os.path.expanduser('~'), DOCKER_CONFIG_FILENAME)`

Therefore changing the plist to specify my home directory makes everything work correctly:

```
<key>EnvironmentVariables</key>
<dict>
  <key>HOME</key>
  <string>/Users/morgan</string>
</dict>
```

Alternatively it could set the `DOCKER_CONFIG` variable.

Not sure how best to integrate this into Dusty's install process, though... thoughts?

**Comment by thieman** [comment]
Thanks for all this info. I've got a working theory now that this might be a bug caused by the progress streaming feature we shipped in 0.7.0.

Up until 0.7.0, every Compose subprocess we run goes through the same plumbing in our `subprocess` module. Part of that module's job is to make sure the Compose process gets demoted to run as your `mac_username` user (`morgan`, in your case) which should point to the correct directory for home.

Starting in 0.7.0, the `dusty up` command invokes the Compose subprocess through [this crazy PTY dance](https://github.com/gamechanger/dusty/blob/0.7.1-RC8/dusty/commands/utils.py#L27). We do this because it's the only way for Compose to stream back to us the progress of downloading and extracting images. However, we aren't demoting to the proper user here, which is probably what's causing your problem. I think all we should need to do is [demote the child](https://github.com/gamechanger/dusty/blob/0.7.1-RC8/dusty/subprocess.py) before it invokes the subprocess and we might get back to the right behavior.

I think it works for you from source because running `sudo` isn't quite the same as actually being the `root` user. Your home dir is still set as morgan's, even though you have root permissions.

**Comment by thieman** [comment]
@morganjbruce I put that fix together and put out an RC with it, could you try to reproduce after running `dusty upgrade 0.7.1-RC9`?

**Comment by morganjbruce** [comment]
@thieman working perfectly, thanks!

**Comment by thieman** [comment]
Hooray :smile: @paetling Could you please end the saga of the longest RC ever and push 0.7.1 sometime this week?

@morganjbruce Thanks again for all your effort digging into this bug!
